server:
  port: 8083

spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 25
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: file-service-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      compression-type: gzip
    properties:
      spring.json.trusted.packages: "*"
      max.request.size: 5242880
      buffer.memory: 5242880

logging:
  level:
    org.springframework: INFO
    org.apache.kafka: INFO
    org.springframework.kafka: INFO
    com.netflix.discovery: INFO
    org.springframework.cloud.netflix.eureka: WARN
    org.apache.hc.client5.http: WARN
    org.apache.hc.client5.http.wire: OFF

topics:
  email-request: email-request
  get-email: get-email
  get-email-reply: get-email-reply

scheduled:
  time-clean-db: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8889/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - info
          - metrics
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    enable:
      all: true
